gui:
  theme:
    selectedLineBgColor:
      - default
  showIcons: true
git:
  pagers:
    - colorArg: always
  commit:
    signOff: false
os:
  editCommand: 'hx'
  editCommandTemplate: '{{editor}} {{filename}}'
