[".config/zsh/.zprezto"]
    type           = "git-repo"
    url            = "https://github.com/sorin-ionescu/prezto.git"
    clone.args     = ["--recurse-submodules"]
    pull.args      = ["--recurse-submodules", "--ff-only"]
