# mise global configuration
# https://mise.jdx.dev/configuration.html

[tools]
kubectl = "1.23.10"
kustomize = "5.8.1"
golang = "1.24.5"
stern = "1.21.0"
# nodejs is managed by volta
rust = "1.85.0"
golangci-lint = "2.3.0"

[settings]
experimental = false
