# mise global configuration
# https://mise.jdx.dev/configuration.html

[tools]
kubectl = "1.35.4"
kustomize = "4.5.7"
golang = "1.26.2"
stern = "1.21.0"
# nodejs is managed by volta
rust = "1.95.0"
golangci-lint = "2.11.4"

[settings]
experimental = false
