# mise global configuration
# https://mise.jdx.dev/configuration.html

[tools]
kubectl = "1.37.0"
kustomize = "4.5.7"
golang = "1.27.1"
stern = "1.34.0"
# nodejs is managed by volta
rust = "1.98.1"
golangci-lint = "2.13.2"

[settings]
experimental = false
